// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// median_polish_summary
NumericVector median_polish_summary(NumericMatrix x, double eps, int maxiter);
RcppExport SEXP _MSstatsdev_median_polish_summary(SEXP xSEXP, SEXP epsSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(median_polish_summary(x, eps, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// get_linear_summary
NumericVector get_linear_summary(const DataFrame& input, const NumericVector& coefs, const NumericMatrix& counts, const bool is_labeled);
RcppExport SEXP _MSstatsdev_get_linear_summary(SEXP inputSEXP, SEXP coefsSEXP, SEXP countsSEXP, SEXP is_labeledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type coefs(coefsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const bool >::type is_labeled(is_labeledSEXP);
    rcpp_result_gen = Rcpp::wrap(get_linear_summary(input, coefs, counts, is_labeled));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSstatsdev_median_polish_summary", (DL_FUNC) &_MSstatsdev_median_polish_summary, 3},
    {"_MSstatsdev_get_linear_summary", (DL_FUNC) &_MSstatsdev_get_linear_summary, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSstatsdev(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
