# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

median_polish_summary <- function(x, eps = 0.01, maxiter = 10L) {
    .Call(`_MSstatsdev_median_polish_summary`, x, eps, maxiter)
}

get_linear_summary <- function(input, coefs, counts, is_labeled) {
    .Call(`_MSstatsdev_get_linear_summary`, input, coefs, counts, is_labeled)
}

